# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pki < Formula
  desc "Quantum-Safe PKI - Certificate Authority toolkit with PQC support"
  homepage "https://github.com/remiblancher/pki"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/remiblancher/pki/releases/download/v0.3.0/pki_0.3.0_darwin_amd64.tar.gz"
      sha256 "313e6672bad378b7c938f78a948fca1b756fb36f2b664931a0922d360ba25982"

      def install
        bin.install "pki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/remiblancher/pki/releases/download/v0.3.0/pki_0.3.0_darwin_arm64.tar.gz"
      sha256 "8ad8b59d0bbc60f90d04555817cd749664b55dbecde13b38eec6deab5ef741f9"

      def install
        bin.install "pki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/pki/releases/download/v0.3.0/pki_0.3.0_linux_amd64.tar.gz"
      sha256 "c48d0e33dbf7a8b3e9b55b853d6f3872e81d791edc525953d49ab3a58b6eb9cd"
      def install
        bin.install "pki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/pki/releases/download/v0.3.0/pki_0.3.0_linux_arm64.tar.gz"
      sha256 "d6bf967e4460570fac359f8fd3935e9056b8ebfe126c430787178d4c035fe28b"
      def install
        bin.install "pki"
      end
    end
  end

  test do
    system "#{bin}/pki", "--version"
  end
end
