# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pki < Formula
  desc "Quantum-Safe PKI - Certificate Authority toolkit with PQC support"
  homepage "https://github.com/remiblancher/pki"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/remiblancher/pki/releases/download/v0.2.0/pki_0.2.0_darwin_amd64.tar.gz"
      sha256 "f172d26cda5e0960e20e279d00a51f59141209fc0075fe598b7ef2009aec0536"

      def install
        bin.install "pki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/remiblancher/pki/releases/download/v0.2.0/pki_0.2.0_darwin_arm64.tar.gz"
      sha256 "b2b3db0fa066e119ce3713ca6d0eb904dd3b62c9a7712973c86691c18047c547"

      def install
        bin.install "pki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/pki/releases/download/v0.2.0/pki_0.2.0_linux_amd64.tar.gz"
      sha256 "0969c460178381ca3757d5e796e139978d2674654a01c9644afc63f484d3c35b"
      def install
        bin.install "pki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/pki/releases/download/v0.2.0/pki_0.2.0_linux_arm64.tar.gz"
      sha256 "bc4066bb622f0ef6bffdf7fe449732f9d299c09f71604063aad8ffa0da20204d"
      def install
        bin.install "pki"
      end
    end
  end

  test do
    system "#{bin}/pki", "--version"
  end
end
