# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qpki < Formula
  desc "Qpki - Certificate Authority toolkit with PQC support"
  homepage "https://github.com/remiblancher/qpki"
  version "0.17.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/remiblancher/qpki/releases/download/v0.17.0/qpki_0.17.0_darwin_amd64.tar.gz"
      sha256 "2d2656aea8251c3425daaae3d0e1430af207bcfbb70930bdffda6e8f673eda3a"

      define_method(:install) do
        bin.install "qpki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/remiblancher/qpki/releases/download/v0.17.0/qpki_0.17.0_darwin_arm64.tar.gz"
      sha256 "e3b4ff732b49e58a4332e00120fb055f95617b8492108c707265924fda19b96a"

      define_method(:install) do
        bin.install "qpki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/qpki/releases/download/v0.17.0/qpki_0.17.0_linux_amd64.tar.gz"
      sha256 "f6d2115e1b9d4bdab1260f8363f5c4233aeefc7a980e3bec0bfdc1576d07373d"
      define_method(:install) do
        bin.install "qpki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/remiblancher/qpki/releases/download/v0.17.0/qpki_0.17.0_linux_arm64.tar.gz"
      sha256 "a6449df81933cbdef0774a20bd0842770ec8b93b3d0d02fcd6262538dfd528f5"
      define_method(:install) do
        bin.install "qpki"
      end
    end
  end

  test do
    system "#{bin}/qpki", "--version"
  end
end
