# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qpki < Formula
  desc "Qpki - Certificate Authority toolkit with PQC support"
  homepage "https://github.com/qpki/qpki"
  version "0.20.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qpki/qpki/releases/download/v0.20.8/qpki_0.20.8_darwin_amd64.tar.gz"
      sha256 "8d4f7fdae56627c74c10e28931074abf55f9f5f05438b41c4d82a60f9a7dc3c7"

      define_method(:install) do
        bin.install "qpki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qpki/qpki/releases/download/v0.20.8/qpki_0.20.8_darwin_arm64.tar.gz"
      sha256 "99ff11a4b76ebb06c08de3053ef4fe294ccc30d79dcdacac1eea29072e4cc1f6"

      define_method(:install) do
        bin.install "qpki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qpki/qpki/releases/download/v0.20.8/qpki_0.20.8_linux_amd64.tar.gz"
      sha256 "012cd8493f49ba26195aeea214287cf875981f0ae3748b7fbe47546169d4670b"
      define_method(:install) do
        bin.install "qpki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qpki/qpki/releases/download/v0.20.8/qpki_0.20.8_linux_arm64.tar.gz"
      sha256 "b1d8525a370703ab19ecdb9a8983e7de383ea0b36b8236ec9b7caabdbfb5e992"
      define_method(:install) do
        bin.install "qpki"
      end
    end
  end

  test do
    system "#{bin}/qpki", "--version"
  end
end
